server:
  port: 8080

spring:
  application:
    name: app-lavitrinacoleccionistas-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 3000
            response-timeout: 10s
          default-filters:
            - AddRequestHeader=X-Gateway, lavitrina
            - AddResponseHeader=X-Gateway, lavitrina
          routes:
            # Rutas de catalogo
            - id: catalogo
              uri: lb://app-lavitrinacoleccionistas-ms-catalogo
              predicates:
                - Path=/api/productos/**,/api/publicaciones/**,/api/ofertas/**
            - id: catalogo-docs
              uri: lb://app-lavitrinacoleccionistas-ms-catalogo
              predicates:
                - Path=/docs/catalogo/v3/api-docs
              filters:
                - RewritePath=/docs/catalogo/(?<p>.*), /api/$\{p}
            #Rutas de intercambio
            - id: intercambios-soporte
              uri: lb://app-lavitrinacoleccionistas-ms-intercambios-soporte
              predicates:
                - Path=/api/intercambios/**,/api/tickets-soporte/**
            - id: intercambios-docs
              uri: lb://app-lavitrinacoleccionistas-ms-intercambios-soporte
              predicates:
                - Path=/docs/intercambios/v3/api-docs
              filters:
                - RewritePath=/docs/intercambios/(?<p>.*), /api/$\{p}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Intercambios y Soporte
        url: /docs/intercambios/v3/api-docs
      - name: Catalogo
        url: /docs/catalogo/v3/api-docs
logging:
  level:
    org.springframework.cloud.gateway: DEBUG